### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by glebfeklistov** [vstirbu/fsm2dot#16]
How to set custom styles?
example 

```
digraph G {
  size="8,5" // <- this style
  node [shape = circle] // <- and this
  connect -> ready [label=" success "]
  start -> connect [label=" try "]
  ready -> connect [label=" try "]
}
```

**Comment by vstirbu** [comment]
The development of this library is done to support this [VSCode plugin](https://github.com/vstirbu/fsm-viewer). You can use that to generate SVG diagrams of the state machines.

Graphviz related functionality is not a priority and it will be removed in the next major release.
